#!/usr/bin/env python3

from KicadModTree import *  # NOQA
from scripts.tools.global_config_files import global_config as GC
from scripts.tools.footprint_scripts_pin_headers import *  # NOQA

# Disclaimer: these configs do not produce the same Pinsockets currently in the footprints repo.
# Those are generated by Connector_Pinsocket by a completely different method.

if __name__ == "__main__":
    global_config = GC.DefaultGlobalConfig()
    class_name = "PinSocket"
    class_description = "socket strip"

    pin_pitch = 2.54
    pins_drill = 1
    pad = [1.7, 1.7]
    body_width_1row = 2.54
    body_offset_1row = 0
    overlength = pin_pitch / 2
    # (right) angled:
    body_width_ra = 8.51
    body_offset_ra = 1.52
    pin_width = 0.64
    pad_offset = 1.25
    pin_length = 2.65
    pin_width = 0.64
    pad_smd = [3, 1]

    lib_name = f"Connector_PinSocket_{pin_pitch:.2f}mm"

    for row_count in [1,2]:
        for num_pos in range(1,41):
            makePinHeadStraight(global_config,
                num_pos, row_count, pin_pitch, pin_pitch, row_count * body_width_1row,
                overlength, overlength, pins_drill, pad, 
                [], lib_name, class_name, class_description, isSocket=True,
                # offset3d=[-(row_count - 1) * pin_pitch / 2 / 25.4, -(num_pos - 1) * pin_pitch / 2 / 25.4, 0], 
                # scale3d=[1, 1, 1],
                # rotate3d=[0, 0, 270], isSocket=True)
            )
            makeSocketStripAngled(global_config,
                num_pos, row_count, pin_pitch, pin_pitch, body_width_ra, body_offset_ra, 
                pin_width, pins_drill, pad,
				[], lib_name,  class_name, class_description,
                # offset3d=[-(row_count - 1) * pin_pitch / 2 / 25.4, -(num_pos - 1) * pin_pitch / 2 / 25.4, 0], 
                # scale3d=[1, 1, 1],
                # rotate3d=[0, 0, 270])
            )
            if row_count == 2:
                makePinHeadStraightSMD(global_config,
                    num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                    pin_length, pin_width, row_count * body_width_1row,
                    overlength, overlength, pad_smd, False,
                    [], lib_name, class_name, class_description, isSocket=True
                )
            # new configs to match the files currently in footprints repo.
            # Those are generated by Connector_PinSocket with different contents.
            elif num_pos != 1:
                    makePinHeadStraightSMD(global_config,
                        num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                        pin_length, pin_width, row_count * body_width_1row,
                        overlength, overlength, pad_smd, False,
                        [], lib_name, class_name, class_description, isSocket=True
                    )
                    makePinHeadStraightSMD(global_config,
                        num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                        pin_length, pin_width, row_count * body_width_1row,
                        overlength, overlength, pad_smd, True,
                        [], lib_name, class_name, class_description, isSocket=True
                    )

    pin_pitch = 2.00
    pins_drill = 0.8
    pad = [1.35, 1.35]
    body_width_1row = 2.0
    overlength = pin_pitch / 2
    # (right) angled:
    body_width_ra = 6.35
    body_offset_ra = 1.27
    pin_width = 0.5
    pad_offset = 2.125
    pin_length = 2
    pin_width = 0.5
    pad_smd = [2.75, 1]

    lib_name = f"Connector_PinSocket_{pin_pitch:.2f}mm"

    for row_count in [1, 2]:
        for num_pos in range(1, 41):
            makePinHeadStraight(global_config,
                num_pos, row_count, pin_pitch, pin_pitch, row_count * body_width_1row,
                overlength, overlength, pins_drill, pad,
                [], lib_name, class_name, class_description, isSocket=True,
                # offset3d=[0,0, 0], 
                # scale3d=[1, 1, 1],
                # rotate3d=[0, 0, 0], isSocket=True)
            )
            makeSocketStripAngled(global_config,
                num_pos, row_count, pin_pitch, pin_pitch, body_width_ra, body_offset_ra,
                pin_width, pins_drill, pad,
                [], lib_name, class_name, class_description,
                # offset3d=[(row_count - 1) * pin_pitch / 2 / 25.4, -(num_pos - 1) * pin_pitch / 2 / 25.4, 0],
                # scale3d=[1, 1, 1],
                # rotate3d=[0, 0, 90])
            )
            if row_count == 2:
                makePinHeadStraightSMD(global_config,
                        num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                        pin_length, pin_width, row_count * body_width_1row,
                        overlength, overlength, pad_smd, False,
                        [], lib_name, class_name, class_description, isSocket=True
                )
            # new configs to match the files currently in footprints repo.
            # Those are generated by Connector_PinSocket with different contents.
            elif num_pos != 1:
                    makePinHeadStraightSMD(global_config,
                        num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                        pin_length, pin_width, row_count * body_width_1row,
                        overlength, overlength, pad_smd, False,
                        [], lib_name, class_name, class_description, isSocket=True
                    )
                    makePinHeadStraightSMD(global_config,
                        num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                        pin_length, pin_width, row_count * body_width_1row,
                        overlength, overlength, pad_smd, True,
                        [], lib_name, class_name, class_description, isSocket=True
                    )

    pin_pitch = 1.27
    pins_drill = 0.7
    pad = [1, 1]
    body_widths = [2.54, 3.05]
    body_width_1row = 1.27
    overlength = pin_pitch / 2
    # (right) angled:
    body_width_ra = 1
    body_offset_ra = 3.81 - 1
    pad_offset = 1.95
    pin_length = 1.92
    pin_width = 0.4
    pad_smd = [2.1, 0.75]

    lib_name = f"Connector_PinSocket_{pin_pitch:.2f}mm"

    for row_count in [1, 2]:
        for num_pos in range(1, 41):
            makePinHeadStraight(global_config,
                num_pos, row_count, pin_pitch, pin_pitch, body_widths[row_count-1],
                overlength, overlength , pins_drill, pad,
                [], lib_name, class_name, class_description, isSocket=True,
                # offset3d=[0, 0, 0], 
                # scale3d=[1, 1, 1],
                # rotate3d=[0, 0, 0], isSocket=True)
            )
            if row_count == 2:
                makePinHeadStraightSMD(global_config,
                        num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                        pin_length, pin_width, row_count * body_width_1row,
                        overlength, overlength, pad_smd, False,
                        [], lib_name, class_name, class_description, isSocket=True
                )
            # new configs to match the files currently in footprints repo.
            # Those are generated by Connector_PinSocket with different contents.
            elif num_pos != 1:
                    makePinHeadStraightSMD(global_config,
                        num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                        pin_length, pin_width, row_count * body_width_1row,
                        overlength, overlength, pad_smd, False,
                        [], lib_name, class_name, class_description, isSocket=True
                    )
                    makePinHeadStraightSMD(global_config,
                        num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                        pin_length, pin_width, row_count * body_width_1row,
                        overlength, overlength, pad_smd, True,
                        [], lib_name, class_name, class_description, isSocket=True
                    )

    for row_count in [2]:
        for num_pos in range(3, 51):
            makeSocketStripAngled(global_config,
                num_pos, row_count, pin_pitch, pin_pitch, body_width_ra, body_offset_ra,
                pin_width, pins_drill, pad,
                [], lib_name,  class_name, class_description,
            )

    # new configs to match the files currently in footprints repo.
    # Those are generated by Connector_PinSocket with different contents.
    pin_pitch = 1.00
    pins_drill = 0.5
    pad = [0.85, 0.85]
    body_widths = [1.5, 2.5]
    overlength = 0.75 + 0.5
    # (right) angled:
    # body_width_ra = 1
    # body_offset_ra = 3.81-1
    pin_width = 0.3
    pad_offset = 1.2
    pin_length = 1.95
    pad_smd = [1.95, 0.50]

    lib_name = f"Connector_PinSocket_{pin_pitch:.2f}mm"

    for row_count in [1, 2]:
        for num_pos in range(2, 41):
            if row_count == 1:
                makePinHeadStraight(global_config,
                    num_pos, row_count, pin_pitch, pin_pitch, body_widths[row_count-1],
                    overlength, overlength , pins_drill, pad,
                    [], lib_name, class_name, class_description, isSocket=True,
                    # offset3d=[0, 0, 0], 
                    # scale3d=[1, 1, 1],
                    # rotate3d=[0, 0, 0], isSocket=True)
                )
            if row_count == 2:
                    makePinHeadStraightSMD(global_config,
                        num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                        pin_length, pin_width, row_count * body_width_1row,
                        overlength, overlength, pad_smd, False,
                        [], lib_name, class_name, class_description, isSocket=True
                    )
            elif num_pos != 1:
                    makePinHeadStraightSMD(global_config,
                        num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                        pin_length, pin_width, row_count * body_width_1row,
                        overlength, overlength, pad_smd, False,
                        [], lib_name, class_name, class_description, isSocket=True
                    )
                    makePinHeadStraightSMD(global_config,
                        num_pos, row_count, pin_pitch, pin_pitch, pad_offset,
                        pin_length, pin_width, row_count * body_width_1row,
                        overlength, overlength, pad_smd, True,
                        [], lib_name, class_name, class_description, isSocket=True
                    )
